CREATE TABLE `menu`(
	`ID` BIGINT(20)  NOT NULL AUTO_INCREMENT,
	`NAME`VARCHAR(255) NOT NULL DEFAULT '' COMMENT '菜单名',
	`LEVEL`INT(11)  NOT NULL DEFAULT 0 COMMENT '菜单级别',
	`PID`BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '菜单父Id',
	`REMARK`VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
	`PERMISSIONS`VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '权限',
	`OPERATOR_ID`BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '操作人',
	`CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间', 
	`UPDATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间', 
	PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '菜单信息';

CREATE TABLE `role`(
	`ID` BIGINT(20)  NOT NULL AUTO_INCREMENT,
	`NAME`VARCHAR(255) NOT NULL DEFAULT '' COMMENT '角色',
	`REMARK`VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
	`IS_SYSTEM`INT(11)  NOT NULL DEFAULT 0 COMMENT '是否是系统内置角色',
	`CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间', 
	`UPDATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间', 
	PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '系统角色';

CREATE TABLE `paike`.`role_menu`(
	`ID` BIGINT(20)  NOT NULL AUTO_INCREMENT,
	`ROLE_ID`BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '角色id',
	`MENU_ID`BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '菜单id',
	`CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间', 
	`UPDATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间', 
	PRIMARY KEY (`id`),
	KEY `IDX_ROLE_MENU` (`ROLE_ID`,`MENU_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '角色菜单配置';

CREATE TABLE `user_role`(
	`ID` BIGINT(20)  NOT NULL AUTO_INCREMENT,
	`ROLE_ID`BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '角色id',
	`STAFF_ID`BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '员工id',
	`NODE_ID`BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '组织架构id',
	`CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间', 
	`UPDATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间', 
	PRIMARY KEY (`id`),
	UNIQUE KEY `UNQ_ROLE` (`USER_ID`,`ROLE_ID`,`NODE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '用户角色';


CREATE TABLE `paike`.`user`(
	`ID` BIGINT(20)  NOT NULL AUTO_INCREMENT,
	`STAFF_ID`BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '员工id',
	`CREATE_TIME` TIMESTAMP NULL COMMENT '创建时间', 
	`UPDATE_TIME` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间', 
	PRIMARY KEY (`id`),
	UNIQUE KEY `UNQ_STAFF` (`STAFF_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '用户表';

CREATE TABLE `organization` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID,自增',
  `ehr_node_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '(ehr系统)组织架构id',
  `code` varchar(10) NOT NULL DEFAULT '' COMMENT '编码',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '名称',
  `ebs_code` varchar(10) NOT NULL DEFAULT '' COMMENT '财务编码（只有分部有）',
  `area_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '区域id',
  `pid` bigint(20) NOT NULL DEFAULT 0 COMMENT '父节点id（关联自增id）',
  `company_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '分公司id（只有分部有分公司）',
  `node_type` bigint(24) NOT NULL DEFAULT 0 COMMENT '节点类型：1，分校；2，分部',
  `CREATE_TIME` datetime NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NULL COMMENT '更新时间',
  `creator_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '创建人id',
  `is_del` tinyint(2) NOT NULL DEFAULT 0 COMMENT '是否删除：0，未删除;1,已删除', 
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组织架构表';

--测试初始化数据
insert into paike.menu (id,name,level,pid,permissions,create_time,update_time) values(1,'权限管理',1,0,'{"200":127,"201":127,"202":127,"203":127,"204":127,"205":127}','2018-07-23 21:50:00','2018-07-23 21:50:00');
insert into paike.role(id,name,remark,is_system,create_time,update_time) values(1,'系统管理员','系统管理员',1,'2018-07-23 21:50:00','2018-07-23 21:50:00');
insert into paike.role_menu(id,role_id,menu_id,create_time,update_time) values(1,1,1,'2018-07-23 21:50:00','2018-07-23 21:50:00');
insert into paike.user(id,staff_id,create_time,update_time) values(1,1,'2018-07-23 21:50:00','2018-07-23 21:50:00');
insert into paike.user_role(id,staff_id,role_id,node_id,create_time,update_time)values(1,1,1,1,'2018-07-23 21:50:00','2018-07-23 21:50:00');