spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: tomcat,jdbc
    include: application-tomcat.yaml,application-jdbc.yaml

mybatis:
  config-location: classpath:mybatis-configuration.xml