spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: tomcat
    include: application-tomcat.yaml,application-jdbc.yaml

mybatis:
  config-location: classpath:mybatis-configuration.xml
#config-location: classpath:mybatis-configuration.xml